// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/connector/projects": {
            "get": {
                "description": "Получение проектов с пагинацией",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get paginated list of Jira projects",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search filter",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structures.ResponseProject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responseutils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responseutils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/connector/updateProject": {
            "post": {
                "description": "Обновляет проект в Jira, загружает задачи и сохраняет их в базу данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update Jira project and push issues to DB",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project Key or ID (required)",
                        "name": "project",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structures.ResponseUpdate"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responseutils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responseutils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responseutils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "responseutils.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "structures.JiraProject": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "response: \".../project\"",
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "self": {
                    "type": "string"
                }
            }
        },
        "structures.PageInfo": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "projectsCount": {
                    "type": "integer"
                }
            }
        },
        "structures.ResponseProject": {
            "type": "object",
            "properties": {
                "pageInfo": {
                    "$ref": "#/definitions/structures.PageInfo"
                },
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/structures.JiraProject"
                    }
                }
            }
        },
        "structures.ResponseUpdate": {
            "type": "object",
            "properties": {
                "project": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/connector",
	Schemes:          []string{},
	Title:            "Jira Connector API",
	Description:      "REST API для взаимодействия с Jira и выгрузки проектов.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
