basePath: /api/v1/connector
definitions:
  responseutils.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  structures.JiraProject:
    properties:
      id:
        description: 'response: ".../project"'
        type: string
      key:
        type: string
      name:
        type: string
      self:
        type: string
    type: object
  structures.PageInfo:
    properties:
      currentPage:
        type: integer
      pageCount:
        type: integer
      projectsCount:
        type: integer
    type: object
  structures.ResponseProject:
    properties:
      pageInfo:
        $ref: '#/definitions/structures.PageInfo'
      projects:
        items:
          $ref: '#/definitions/structures.JiraProject'
        type: array
    type: object
  structures.ResponseUpdate:
    properties:
      project:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API для взаимодействия с Jira и выгрузки проектов.
  title: Jira Connector API
  version: "1.0"
paths:
  /api/v1/connector/projects:
    get:
      consumes:
      - application/json
      description: Получение проектов с пагинацией
      parameters:
      - description: Items per page
        in: query
        name: limit
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Search filter
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structures.ResponseProject'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responseutils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responseutils.ErrorResponse'
      summary: Get paginated list of Jira projects
      tags:
      - projects
  /api/v1/connector/updateProject:
    post:
      consumes:
      - application/json
      description: Обновляет проект в Jira, загружает задачи и сохраняет их в базу
        данных
      parameters:
      - description: Project Key or ID (required)
        in: query
        name: project
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structures.ResponseUpdate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responseutils.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responseutils.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responseutils.ErrorResponse'
      summary: Update Jira project and push issues to DB
      tags:
      - projects
swagger: "2.0"
