version: '3'

vars:
  COMPOSE_FILE: deployment/docker-compose.yaml

tasks:
  build:
    desc: Сборка Docker образов
    cmds:
      - docker compose build

  unit-test:
    desc: Юнит-тесты Go (В ПРОЦЕССЕ РАЗРАБОТКИ)
    cmds:
      - echo "Запуск юнит-тестов эндпоинтов ПОКА НЕ РАБОТАЕТ"
      #- docker compose run --rm backend go test ./... -v

      - echo "Запуск юнит-тестов коннектора ПОКА НЕ РАБОТАЕТ"
      #- docker compose run --rm jiraconnector go test ./... -v

  integration-test:
    desc: Интеграционные тесты
    cmds:
      # Запуск интеграционных тестов для коннектора
      - docker compose run --rm jiraconnector go test ./tests/integration/... -v -tags=integration

      # Запуск интеграционных тестов для всей системы
      - docker compose run --rm backend-test

  up:
    desc: Запуск приложения
    cmds:
      - docker compose up -d

  all:
    desc: Полный пайплайн [ build -> unit-test -> integration-test -> up ]
    cmds:
      - task: build
      - task: unit-test
      - task: integration-test
      - task: up

  down:
    desc: Остановить контейнеры
    cmds:
      - docker compose down

  clean:
    desc: Полная очистка контейнеров и мусора
    cmds:
      - docker compose down -v --remove-orphans

  logs:
    desc: Логи всех сервисов (кроме коннектора :D)
    cmds:
      - docker compose logs -f
  
  logs-connector:
    desc: Логи jira-connector
    cmds:
      - docker exec -it deployment-jiraconnector-1 cat log/jiraconnector.log
  
  db:
    desc: Консоль базы данных
    cmds:
      - docker exec -it deployment-postgres-1 psql -U postgres -d testdb
